<?php include 'robots.php'; ?>
<?php include 'title.php'; ?>
<?php include 'description.php'; ?>
<?php include 'image.php'; ?>
<?php include 'icon.php'; ?>
<?php include 'theme.php'; ?>
<?php include 'sitename.php'; ?>
<?php include 'type.php'; ?>
<?php include 'author.php'; ?>
<?php include 'canonical.php'; ?>
<?php include 'referrer.php'; ?>
<?php include 'copyright.php'; ?>
<?php include 'other.php'; ?>